expgroup: test
expname: ${expgroup}_${now:%m-%d_%H-%M}

core:
  version: 0.0.1
  tags:
    - ${expgroup}
    - Year=${now:%Y}
    - Month=${now:%m}
    - Day=${now:%d}

defaults:
  - _self_
  - data: default
  - hydra: default
  - logging: default
  - model: vae
  - optim: default
  - train: default
#    Decomment this parameter to get parallel job running
  # - override hydra/launcher: joblib
